//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ProjectRevision5.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProjectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProjectEntities object using the connection string found in the 'ProjectEntities' section of the application configuration file.
        /// </summary>
        public ProjectEntities() : base("name=ProjectEntities", "ProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjectEntities object.
        /// </summary>
        public ProjectEntities(string connectionString) : base(connectionString, "ProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjectEntities object.
        /// </summary>
        public ProjectEntities(EntityConnection connection) : base(connection, "ProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Task> Tasks
        {
            get
            {
                if ((_Tasks == null))
                {
                    _Tasks = base.CreateObjectSet<Task>("Tasks");
                }
                return _Tasks;
            }
        }
        private ObjectSet<Task> _Tasks;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTasks(Task task)
        {
            base.AddObject("Tasks", task);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectModel", Name="Task")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Task : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Task object.
        /// </summary>
        /// <param name="row_ID">Initial value of the Row_ID property.</param>
        /// <param name="task_Name">Initial value of the Task_Name property.</param>
        public static Task CreateTask(global::System.Int32 row_ID, global::System.String task_Name)
        {
            Task task = new Task();
            task.Row_ID = row_ID;
            task.Task_Name = task_Name;
            return task;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Row_ID
        {
            get
            {
                return _Row_ID;
            }
            set
            {
                if (_Row_ID != value)
                {
                    OnRow_IDChanging(value);
                    ReportPropertyChanging("Row_ID");
                    _Row_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Row_ID");
                    OnRow_IDChanged();
                }
            }
        }
        private global::System.Int32 _Row_ID;
        partial void OnRow_IDChanging(global::System.Int32 value);
        partial void OnRow_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Task_Name
        {
            get
            {
                return _Task_Name;
            }
            set
            {
                OnTask_NameChanging(value);
                ReportPropertyChanging("Task_Name");
                _Task_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Task_Name");
                OnTask_NameChanged();
            }
        }
        private global::System.String _Task_Name;
        partial void OnTask_NameChanging(global::System.String value);
        partial void OnTask_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Start_Time
        {
            get
            {
                return _Start_Time;
            }
            set
            {
                OnStart_TimeChanging(value);
                ReportPropertyChanging("Start_Time");
                _Start_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start_Time");
                OnStart_TimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Start_Time;
        partial void OnStart_TimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStart_TimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> End_Time
        {
            get
            {
                return _End_Time;
            }
            set
            {
                OnEnd_TimeChanging(value);
                ReportPropertyChanging("End_Time");
                _End_Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End_Time");
                OnEnd_TimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _End_Time;
        partial void OnEnd_TimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEnd_TimeChanged();

        #endregion
    
    }

    #endregion
    
}
